// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9snWL_F6zb5DWw3v6TgCm2vYl6ZCpR00',
    appId: '1:61252148722:web:626e51fbed94dc8bc7df6b',
    messagingSenderId: '61252148722',
    projectId: 'assignment-ict602',
    authDomain: 'assignment-ict602.firebaseapp.com',
    storageBucket: 'assignment-ict602.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_GuFoNAQMrwDLfxSeF5wHJgBFJ623oiA',
    appId: '1:61252148722:android:50f160e81e880538c7df6b',
    messagingSenderId: '61252148722',
    projectId: 'assignment-ict602',
    storageBucket: 'assignment-ict602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Aan3c3eisDa-TgQsqMRmFc2aoIig9EY',
    appId: '1:61252148722:ios:5545660722a2ff88c7df6b',
    messagingSenderId: '61252148722',
    projectId: 'assignment-ict602',
    storageBucket: 'assignment-ict602.firebasestorage.app',
    iosClientId: '61252148722-lgh5t91mjmvaogp38bs1hbf0onemf72j.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentIct602',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Aan3c3eisDa-TgQsqMRmFc2aoIig9EY',
    appId: '1:61252148722:ios:5545660722a2ff88c7df6b',
    messagingSenderId: '61252148722',
    projectId: 'assignment-ict602',
    storageBucket: 'assignment-ict602.firebasestorage.app',
    iosClientId: '61252148722-lgh5t91mjmvaogp38bs1hbf0onemf72j.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentIct602',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9snWL_F6zb5DWw3v6TgCm2vYl6ZCpR00',
    appId: '1:61252148722:web:81051fab8bbc2d2fc7df6b',
    messagingSenderId: '61252148722',
    projectId: 'assignment-ict602',
    authDomain: 'assignment-ict602.firebaseapp.com',
    storageBucket: 'assignment-ict602.firebasestorage.app',
  );
}
